### ISSUE TITLE
is there a delete function?

### ISSUE THREAD

**Issue by hiqsociety** [clarkmcc/go-evmap#1]
can u pls provide benchmark against fastcache from victoria metrics and bigcache from allegro?

**Comment by clarkmcc** [comment]
Hi @hiqsociety. Great idea, however this project is a research project rather than a production-ready data structure. See README
> Note: Note: this is not a production-ready data structure by any-means. It is currently a work-in-progress exploration of a left-right-backed concurrent map. 

I won't be pouring much time into performance benchmarks until the data structure's behavior is correct.
